version: "3.9"
services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: django_db
    volumes:
      - db_data:/var/lib/postgresql/data/
    networks:
      - django_net

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - django_net

networks:
  django_net:

volumes:
  db_data:
