# Generated by Django 4.1.7 on 2023-03-29 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('BIS', 'Business'), ('CUS', 'Customer')], default='CUS', max_length=3),
            preserve_default=False,
        ),
    ]
